version: "3.9"
services:
  myelectricaldata_flex:
    image: gandulf78/myelectricaldata:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./log:/log
    environment:
      TZ: Europe/Paris
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s